error
Python 3.9.7: /home/mcqueen-zero/anaconda3/envs/imgproapp/bin/python
Thu Apr 21 17:27:55 2022

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /home/mcqueen-zero/PycharmProjects/img-proc-app/gui/maingui_edit.py in save_as(self=<gui.maingui_edit.Ui_MainWindow object>)
  445                                                       'PNG 文件(*.png);; JPG 文件(*.jpg);; JPEG 文件(*.jpeg)',
  446                                                       'JPG 文件(*.jpg)')
  447             self.frame_2.CV.saveimg(filepath)
  448 
  449     def copy(self):
self = <gui.maingui_edit.Ui_MainWindow object>
self.frame_2 = <widgets.ImgFrame.ImgFrame object>
self.frame_2.CV = <plugins.ipc.AppImg object>
self.frame_2.CV.saveimg = <bound method AppImg.saveimg of <plugins.ipc.AppImg object>>
filepath = '/home/mcqueen-zero/PycharmProjects/img-proc-app/a'

 /home/mcqueen-zero/PycharmProjects/img-proc-app/plugins/ipc.py in saveimg(self=<plugins.ipc.AppImg object>, imgfilepath='/home/mcqueen-zero/PycharmProjects/img-proc-app/a')
   90                 imencode(ext, self.img)[1].tofile(imgfilepath)
   91             else:
   92                 imwrite(imgfilepath, self.img)
   93 
   94     def Q2CVimg(self, Qimg: QImage):
global imwrite = <built-in function imwrite>
imgfilepath = '/home/mcqueen-zero/PycharmProjects/img-proc-app/a'
self = <plugins.ipc.AppImg object>
self.img = array([[[ 13,  55,   2],
        [ 14,  56,   3]...55, 151],
        [174, 165, 161]]], dtype=uint8)
error: OpenCV(4.5.5) /io/opencv/modules/imgcodecs/src/loadsave.cpp:730: error: (-2:Unspecified error) could not find a writer for the specified extension in function 'imwrite_'

    __cause__ = None
    __class__ = <class 'cv2.error'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of error object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of error object>
    __doc__ = None
    __eq__ = <method-wrapper '__eq__' of error object>
    __format__ = <built-in method __format__ of error object>
    __ge__ = <method-wrapper '__ge__' of error object>
    __getattribute__ = <method-wrapper '__getattribute__' of error object>
    __gt__ = <method-wrapper '__gt__' of error object>
    __hash__ = <method-wrapper '__hash__' of error object>
    __init__ = <method-wrapper '__init__' of error object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of error object>
    __lt__ = <method-wrapper '__lt__' of error object>
    __module__ = 'cv2'
    __ne__ = <method-wrapper '__ne__' of error object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of error object>
    __reduce_ex__ = <built-in method __reduce_ex__ of error object>
    __repr__ = <method-wrapper '__repr__' of error object>
    __setattr__ = <method-wrapper '__setattr__' of error object>
    __setstate__ = <built-in method __setstate__ of error object>
    __sizeof__ = <built-in method __sizeof__ of error object>
    __str__ = <method-wrapper '__str__' of error object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    __weakref__ = None
    args = ("OpenCV(4.5.5) /io/opencv/modules/imgcodecs/src/l...r the specified extension in function 'imwrite_'\n",)
    code = -2
    err = 'could not find a writer for the specified extension'
    file = '/io/opencv/modules/imgcodecs/src/loadsave.cpp'
    func = 'imwrite_'
    line = 730
    msg = "OpenCV(4.5.5) /io/opencv/modules/imgcodecs/src/l...r the specified extension in function 'imwrite_'\n"
    with_traceback = <built-in method with_traceback of error object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/home/mcqueen-zero/PycharmProjects/img-proc-app/gui/maingui_edit.py", line 447, in save_as
    self.frame_2.CV.saveimg(filepath)
  File "/home/mcqueen-zero/PycharmProjects/img-proc-app/plugins/ipc.py", line 92, in saveimg
    imwrite(imgfilepath, self.img)
cv2.error: OpenCV(4.5.5) /io/opencv/modules/imgcodecs/src/loadsave.cpp:730: error: (-2:Unspecified error) could not find a writer for the specified extension in function 'imwrite_'


